# Generated by Django 3.0.6 on 2020-05-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_saeed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saeed',
        ),
    ]
