# Generated by Django 3.0.6 on 2020-05-08 15:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oreder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('userPhone', models.CharField(max_length=200)),
                ('useraddress', models.CharField(max_length=600)),
                ('email', models.EmailField(max_length=254)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateTimeField(default=datetime.datetime.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
        ),
    ]
